version: 2.1

commands:
  install_deps:
    description: "Install dependencies"
    steps:
      - run:
          name: "Install dependencies"
          command: |
            sudo apt -q update
            sudo apt install -qy libgmp-dev

  build_and_test:
    description: "Build & Test"
    steps:
      - run:
          name: "Environment"
          command: |
            CC=${CC:-cc}
            CXX=${CXX:-cpp}
            echo CC: $CC
            echo CXX: $CXX
            $CC --version
            $CXX --version
            cmake --version
      - checkout
      - run:
          name: "Configure"
          working_directory: ~/build
          command: cmake ../project -DCMAKE_INSTALL_PREFIX=~/install -DCMAKE_BUILD_TYPE=$BUILD_TYPE $CMAKE_OPTIONS
      - run:
          name: "Build"
          working_directory: ~/build
          command: |
            cmake --build . -- -j4
            cmake --build . --target install
            cmake --build . --target package
      - run:
          name: "Test"
          working_directory: ~/build
          command: |
            ctest -j4 --output-on-failure --schedule-random -R ${TESTS_FILTER:-'.*'} -E ${TESTS_EXCLUDE}
      - run:
          name: "Install"
          command: cmake --build ~/build --target install

  benchmark:
    description: "Benchmark"
    steps:
      - run:
          name: "Benchmark"
          working_directory: ~/build
          command: test/intx-bench --benchmark_min_time=0.01


jobs:

  build-minimal:
    docker:
      - image: ethereum/cpp-build-env:14-gcc-10
    steps:
      - checkout
      - run:
          name: "Build package"
          working_directory: ~/build
          command: |
            cmake ../project -DINTX_TESTING=OFF
            cmake --build . --target package
      - run:
          name: "Inspect package"
          command: tar tvf ~/build/intx*.tar.gz

  linux-gcc-debug:
    environment:
      - BUILD_PARALLEL_JOBS: 4
      - BUILD_TYPE: Debug
      - TESTS_FILTER: unittests
      - TESTS_EXCLUDE: random
    docker:
      - image: ethereum/cpp-build-env:14-gcc-10
    steps:
      - install_deps
      - build_and_test

  linux-clang-coverage:
    environment:
      - BUILD_PARALLEL_JOBS: 4
      - BUILD_TYPE: Coverage
      - TESTS_FILTER: unittests
      - TESTS_EXCLUDE: random
    docker:
      - image: ethereum/cpp-build-env:14-clang-10
    steps:
      - install_deps
      - build_and_test
      - run:
          name: "Coverage"
          working_directory: ~/build
          command: |
            mkdir coverage
            find -name '*.profraw'
            llvm-profdata merge *.profraw -o intx.profdata
            llvm-cov report -use-color -instr-profile intx.profdata -Xdemangler llvm-cxxfilt test/intx-unittests
            llvm-cov report -instr-profile intx.profdata -Xdemangler llvm-cxxfilt test/intx-unittests > coverage/report.txt
            llvm-cov show -format=html -instr-profile intx.profdata -Xdemangler llvm-cxxfilt -region-coverage-lt=100 test/intx-unittests > coverage/missing.html
            llvm-cov show -format=html -instr-profile intx.profdata -Xdemangler llvm-cxxfilt test/intx-unittests > coverage/full.html
            llvm-cov export -instr-profile intx.profdata -format=lcov test/intx-unittests > intx.lcov
            genhtml intx.lcov -o coverage -t intx
      - store_artifacts:
          path: ~/build/coverage
          destination: coverage
      - run:
          name: "Upload to Codecov"
          command: |
            sudo pip3 install --upgrade --quiet --no-cache-dir codecov
            # Convert to relative paths
            sed -i 's|$(pwd)/||' ~/build/intx.lcov
            codecov --required --file ~/build/intx.lcov -X gcov


  linux-clang-sanitizers:
    environment:
      - BUILD_PARALLEL_JOBS: 4
      - BUILD_TYPE: RelWithDebInfo
      - CMAKE_OPTIONS: -DSANITIZE=address,undefined,implicit-conversion,nullability -DCMAKE_CXX_CLANG_TIDY=clang-tidy
      - UBSAN_OPTIONS: halt_on_error=1
    docker:
      - image: ethereum/cpp-build-env:14-clang-10
    steps:
      - install_deps
      - build_and_test
      - benchmark

  no-exceptions:
    environment:
      - BUILD_TYPE: Release
      - CMAKE_OPTIONS: -DEXCEPTIONS=OFF -DRTTI=OFF
    docker:
      - image: ethereum/cpp-build-env:14-gcc-10
    steps:
      - install_deps
      - build_and_test
      - benchmark

  linux-32bit:
    environment:
      - BUILD_PARALLEL_JOBS: 4
      - BUILD_TYPE: Release
      - CMAKE_OPTIONS: -DCMAKE_TOOLCHAIN_FILE=~/project/cmake/toolchains/32bit.cmake -DINTX_BENCHMARKING=OFF
    docker:
      - image: ethereum/cpp-build-env:14-gcc-10-multilib
    steps:
      - build_and_test

  fuzzing:
    environment:
      - BUILD_PARALLEL_JOBS: 4
      - BUILD_TYPE: Release
      - CMAKE_OPTIONS: -DINTX_FUZZING=ON
    docker:
      - image: ethereum/cpp-build-env:14-clang-10
    steps:
      - install_deps
      - build_and_test
      - benchmark
      - restore_cache:
          keys:
            - corpus
      - run:
          name: "Fuzzing"
          working_directory: ~/build
          command: |
            mkdir -p ~/corpus
            test/intx-fuzzer ~/corpus -use_value_profile=1 -max_len=129 -runs=1000000 -jobs=4
      - save_cache:
          key: corpus-{{ epoch }}
          paths:
            - ~/corpus

  macos:
    environment:
      BUILD_TYPE: Release
      BUILD_PARALLEL_JOBS: 8
      TEST_PARALLEL_JOBS: 8
    macos:
      xcode: 11.5.0
    steps:
      - run:
          name: "Install deps"
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake gmp
      - build_and_test
      - benchmark


  cmake-min:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - run:
          name: "Install default CMake"
          command: sudo apt -q update && sudo apt -qy install cmake
      - build_and_test

workflows:
  version: 2
  intx:
    jobs:
      - build-minimal
      - linux-gcc-debug
      - linux-clang-coverage
      - linux-clang-sanitizers
      - no-exceptions
      - linux-32bit
      - fuzzing
      - macos
      - cmake-min
